POST http://localhost:2468/blockchain
Content-Type: application/json

{
  "nom": "Alan Turing",
  "don": 4567
}

<> 2024-01-25T165132.200.json

###
GET http://localhost:2468/blockchain
Accept: application/json

<> 2024-01-25T153658.200.json
<> 2024-01-25T153407.200.json

###